server:
  port: 8000
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: "warn"
    org:
      springframework:
        web: "debug"
        data:
          rest: "debug"

spring:
  application:
    name: ZeroDay

  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:mysql://${DB_HOST}/${DB_DATABASE}

  jackson:
    time-zone: UTC
    mapper:
      '[ACCEPT_CASE_INSENSITIVE_ENUMS]': true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    open-in-view: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  rsa:
    private-key: classpath:certs/private-key.pem
    public-key: classpath:certs/public-key.pem

  token:
    expiration-time: 24
    time-unit: HOURS

aws:
  s3:
    region: us-east-1
    bucket-name: ecommerce-ayds
