server:
  port: 8000
  error:
    include-message: always
    include-binding-errors: always

  servlet:
    contextPath: /api

spring:
  application:
    name: ZeroDay

  data:
    rest:
      detection-strategy: annotated

  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:mysql://${DB_HOST}/${DB_DATABASE}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

    open-in-view: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

aws:
  s3:
    region: us-east-1
    bucketName: ecommerce-ayds
